Fix for broken JUnit test in the common code. TestXmlUtility.testNodeToXmlString() needs the serializer.jar file at run-time. It had been failing with the error message:
org/apache/xml/serializer/TreeWalker

java.lang.NoClassDefFoundError: org/apache/xml/serializer/TreeWalker
at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:823)
at edu.lternet.pasta.common.XmlUtility.nodeToXmlString(XmlUtility.java:82)
at edu.lternet.pasta.common.TestXmlUtility.testNodeToXmlString(TestXmlUtility.java:83)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.serializer.TreeWalker
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)